language: objective-c
osx_image: xcode7.2

env:
  global:
    - secure: F3cShv/BpzUj5OR7tM20iu8qvekAKIwP1mvwurLVb5iigG1AEj/omU5t/xUFA85pGZkOKqxxOMWtH5rAUQf4Wt5M/aNe8uka7X0Toj//mkRnrRVRryMbljB3wUxqJLCOOP1ZHV9k1I7kpOvFdormxsNVPgbUcxAgzvX+pN9J1RFi+9h/YbeDINg7uXI0mraQBapGDYRC6L6X29uKVTTAhuB7AD+CG/lLKZoXyMWS4fOW+pgBDP5+KCkahoR3PLQID8BbEjIT++drw2ujHMU1avOLBjGoilUDMMcsd8ACOJQQifDu+grScDTYKJ/4KSAsYipiDoeQBC3MT6L/aD7vTyJsBVOkdB4YYbQPEHQ4NrcnY6uG6o7BhzM8T4YJDDAC9wlYULqc5DfrEIYoAXI0yVI3haQGA89k2FFqffi8/hDH8n3deWDDL16liWdT5ecHaqmwTdAeVSLdPvrMszX6E9zvwyOPZAtpFEmWVycAgDPx4eJt/J3w4MB0HW31lYBbraoPdLP2VvkScghVKe1tPxnnOQNotHHACKU6JdVEj9aOmIb+LmQ8TT4TGCXJpjdRhtAj2urSb6FN/XPlvc6pJ9kQvumINWVlQLU4H/LYfBJkodlOHBjR18EyCjBKQRCQgv0EEE4Ap8gMf6rc0vM7BR35/YX1hntYG+WXTgqPgxg=

install:
  - carthage bootstrap --use-submodules --no-build

script:
  - set -o pipefail
  - xcodebuild -workspace WooCommerceSDK.xcworkspace -scheme WooCommerceSDK-iOS -sdk iphonesimulator9.2 -destination "OS=9.2,name=iPhone 6s Plus" ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - xcodebuild -workspace WooCommerceSDK.xcworkspace -scheme WooCommerceSDK-tvOS -sdk appletvsimulator9.1 -destination "OS=9.1,name=Apple TV 1080p" ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - xcodebuild -workspace WooCommerceSDK.xcworkspace -scheme WooCommerceSDK-watchOS -sdk watchsimulator2.1 -destination "OS=2.1,name=Apple Watch - 42mm" ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - xcodebuild test -workspace WooCommerceSDK.xcworkspace -scheme WooCommerceSDK-OSX | xcpretty -c
